[project]
name = "streamlit-app-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.21.0",
    "streamlit>=1.41.1",
]
